name: Update Wiki

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
  pull_request:
    types: [closed]
    paths:
      - 'docs/**'

jobs:
  update-wiki:
    # Only run for push events, or for pull_request closed events where the PR was merged.
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies (if any)
        run: |
          if [ -f package.json ]; then npm ci; fi

      - name: Run wiki init and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          node scripts/init-wiki.js --docs docs/wiki
